# Generated by Django 5.2.1 on 2025-05-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='services.service', verbose_name='Оказываемые услуги'),
        ),
    ]
