# Generated by Django 5.2.1 on 2025-05-30 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='work_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='work_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
