# Generated by Django 5.2.7 on 2025-10-01 18:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_delete_department_doctorprofile_work_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Профиль врача', 'verbose_name_plural': 'Профили врачей'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость консультации'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен для записи'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Номер лицензии'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialization', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='work_end',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='work_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
