# Generated by Django 5.2.1 on 2025-05-29 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_doctorprofile_department_and_more'),
        ('appointments', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.clientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.doctorprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service'),
        ),
    ]
