# Generated by Django 5.2.7 on 2025-10-01 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0002_service_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Профиль клиента', 'verbose_name_plural': 'Профили клиентов'},
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Аллергии'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контакт в экстренной ситуации'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон экстренного контакта'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='medical_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер медицинской карты'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='medical_history',
            field=models.TextField(blank=True, null=True, verbose_name='Медицинская история'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_language',
            field=models.CharField(default='русский', max_length=50, verbose_name='Предпочитаемый язык'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.cart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
                'unique_together': {('cart', 'service')},
            },
        ),
    ]
