# Generated by Django 5.2 on 2025-10-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientprofile_options_and_more'),
        ('doctors', '0006_link_doctors_to_services'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время приема'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctorprofile', verbose_name='Врач'),
        ),
    ]
