# Generated by Django 5.2.1 on 2025-05-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_department_specialization_clientprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='first_name',
            field=models.CharField(default='Имя', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_name',
            field=models.CharField(default='Имя', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите номер телефона в формате +375XXXXXXXXX', max_length=20, null=True),
        ),
    ]
