# Generated by Django 5.2.1 on 2025-05-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_doctorprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
