# Generated by Django 5.2.1 on 2025-05-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_doctorprofile_category_and_more'),
        ('appointments', '0003_alter_appointment_client_alter_appointment_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
