# Generated by Django 5.2.7 on 2025-10-01 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_service_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('link_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст ссылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала показа')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания показа')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент'), ('fixed', 'Фиксированная сумма')], max_length=10, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер скидки')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма заказа')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная сумма скидки')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит использований')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, verbose_name='Лимит на пользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('valid_from', models.DateTimeField(verbose_name='Действителен с')),
                ('valid_until', models.DateTimeField(verbose_name='Действителен до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('applicable_services', models.ManyToManyField(blank=True, to='services.service', verbose_name='Применимые услуги')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='ID заказа')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер скидки')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'ordering': ['-used_at'],
            },
        ),
    ]
